export { default as imagePartnerAccountingImage } from './partner-accounting.png'
export { default as imageBusinessAccounts } from './business-accounts.svg'
export { default as imageBusinessOverview } from './business-overview.svg'
export { default as imageCategorizeExpenses } from './categorize-expenses.svg'
export { default as imageBookkeeperInquiries } from './bookkeeper-inquiries.svg'
export { default as imageScheduleBookkeeperMeeting } from './schedule-bookkeeper-meeting.svg'
export { default as imagePnlOverview } from './pnl-overview.svg'
