import type { ListBookkeepingPeriodsResponse } from '@schemas/bookkeepingPeriods'
import { BookkeepingPeriodStatus } from '@schemas/bookkeepingPeriods'
import { BookkeepingPeriodScale } from '@schemas/bookkeepingPeriods'
import { TasksStatus } from '@schemas/bookkeepingPeriods'
import { TasksResponseType } from '@schemas/bookkeepingPeriods'
import { DocumentType } from '@schemas/bookkeepingPeriods'

export const MOCK_BOOKKEEPING_PERIODS_RESPONSE: ListBookkeepingPeriodsResponse = {
  data: {
    periods: [
      {
        id: '550e8400-e29b-41d4-a716-446655440000',
        month: 11,
        year: 2025,
        status: BookkeepingPeriodStatus.IN_PROGRESS_AWAITING_CUSTOMER,
        scale: BookkeepingPeriodScale.MONTHLY,
        tasks: [
          {
            id: '660e8400-e29b-41d4-a716-446655440001',
            question: 'Please upload your bank statements for November 2025',
            status: TasksStatus.TODO,
            title: 'Upload Bank Statements',
            transactionId: null,
            type: 'UPLOAD_DOCUMENT',
            userMarkedCompletedAt: null,
            userResponse: null,
            userResponseType: TasksResponseType.UPLOAD_DOCUMENT,
            archivedAt: null,
            completedAt: null,
            createdAt: new Date('2025-11-01T00:00:00Z'),
            updatedAt: new Date('2025-11-01T00:00:00Z'),
            effectiveDate: new Date('2025-11-01T00:00:00Z'),
            documentType: DocumentType.BANK_STATEMENT,
            documents: [],
          },
          {
            id: '660e8400-e29b-41d4-a716-446655440002',
            question: 'Please upload receipts for November 2025 expenses',
            status: TasksStatus.TODO,
            title: 'Upload Receipts',
            transactionId: null,
            type: 'UPLOAD_DOCUMENT',
            userMarkedCompletedAt: null,
            userResponse: null,
            userResponseType: TasksResponseType.UPLOAD_DOCUMENT,
            archivedAt: null,
            completedAt: null,
            createdAt: new Date('2025-11-01T00:00:00Z'),
            updatedAt: new Date('2025-11-01T00:00:00Z'),
            effectiveDate: new Date('2025-11-01T00:00:00Z'),
            documentType: DocumentType.RECEIPT,
            documents: [],
          },
          {
            id: '660e8400-e29b-41d4-a716-446655440003',
            question: 'Please provide clarification on transaction #12345',
            status: TasksStatus.TODO,
            title: 'Clarify Transaction',
            transactionId: '770e8400-e29b-41d4-a716-446655440004',
            type: 'FREE_RESPONSE',
            userMarkedCompletedAt: null,
            userResponse: null,
            userResponseType: TasksResponseType.FREE_RESPONSE,
            archivedAt: null,
            completedAt: null,
            createdAt: new Date('2025-11-05T00:00:00Z'),
            updatedAt: new Date('2025-11-05T00:00:00Z'),
            effectiveDate: new Date('2025-11-05T00:00:00Z'),
            documentType: DocumentType.OTHER,
            documents: [],
          },
        ],
      },
      // {
      //   id: '550e8400-e29b-41d4-a716-446655440005',
      //   month: 0,
      //   year: 2025,
      //   status: BookkeepingPeriodStatus.IN_PROGRESS_AWAITING_CUSTOMER,
      //   scale: BookkeepingPeriodScale.ANNUALLY,
      //   tasks: [
      //     {
      //       id: '660e8400-e29b-41d4-a716-446655440006',
      //       question: 'Please provide loan amortization documentation for 2025',
      //       status: TasksStatus.TODO,
      //       title: 'Request for Loan Amortization Docs',
      //       transactionId: null,
      //       type: 'UPLOAD_DOCUMENT',
      //       userMarkedCompletedAt: null,
      //       userResponse: null,
      //       userResponseType: TasksResponseType.UPLOAD_DOCUMENT,
      //       archivedAt: null,
      //       completedAt: null,
      //       createdAt: new Date('2025-01-01T00:00:00Z'),
      //       updatedAt: new Date('2025-01-01T00:00:00Z'),
      //       effectiveDate: new Date('2025-01-01T00:00:00Z'),
      //       documentType: DocumentType.LOAN_STATEMENT,
      //       documents: [],
      //     },
      //   ],
      // },
      // {
      //   id: '550e8400-e29b-41d4-a716-446655440007',
      //   month: 0,
      //   year: 0,
      //   status: BookkeepingPeriodStatus.IN_PROGRESS_AWAITING_CUSTOMER,
      //   scale: BookkeepingPeriodScale.ONGOING,
      //   tasks: [
      //     {
      //       id: '660e8400-e29b-41d4-a716-446655440008',
      //       question: 'Please reconnect your Plaid account',
      //       status: TasksStatus.TODO,
      //       title: 'Reconnect Plaid',
      //       transactionId: null,
      //       type: 'FREE_RESPONSE',
      //       userMarkedCompletedAt: null,
      //       userResponse: null,
      //       userResponseType: TasksResponseType.FREE_RESPONSE,
      //       archivedAt: null,
      //       completedAt: null,
      //       createdAt: new Date('2025-01-01T00:00:00Z'),
      //       updatedAt: new Date('2025-01-01T00:00:00Z'),
      //       effectiveDate: new Date('2025-01-01T00:00:00Z'),
      //       documentType: DocumentType.OTHER,
      //       documents: [],
      //     },
      //     {
      //       id: '660e8400-e29b-41d4-a716-446655440009',
      //       question: 'Please send business permit with correct TIN',
      //       status: TasksStatus.TODO,
      //       title: 'Send Business Permit with Correct TIN',
      //       transactionId: null,
      //       type: 'UPLOAD_DOCUMENT',
      //       userMarkedCompletedAt: null,
      //       userResponse: null,
      //       userResponseType: TasksResponseType.UPLOAD_DOCUMENT,
      //       archivedAt: null,
      //       completedAt: null,
      //       createdAt: new Date('2025-01-01T00:00:00Z'),
      //       updatedAt: new Date('2025-01-01T00:00:00Z'),
      //       effectiveDate: new Date('2025-01-01T00:00:00Z'),
      //       documentType: DocumentType.OTHER,
      //       documents: [],
      //     },
      //   ],
      // },
    ],
  },
}
