export enum LedgerAccountTypeOrderEnum {
  ASSET,
  LIABILITY,
  EQUITY,
  REVENUE,
  EXPENSES,
}

export enum LedgerAccountSubtypeOrderEnum {
  // ASSET
  BANK_ACCOUNTS,
  CASH,
  UNDEPOSITED_FUNDS,
  PAYMENT_PROCESSOR_CLEARING_ACCOUNT,
  INBOUND_PAYMENT_METHOD_CLEARING,
  ACCOUNTS_RECEIVABLE,
  INVENTORY,
  CURRENT_ASSET,
  FIXED_ASSET,
  INTANGIBLE_ASSET,
  PREPAID_EXPENSES,
  DEVELOPMENT_COSTS,

  // LIABILITY
  CREDIT_CARD,
  ACCOUNTS_PAYABLE,
  LINE_OF_CREDIT,
  REFUND_LIABILITIES,
  PAYROLL_LIABILITY,
  SALES_TAXES_PAYABLE,
  OTHER_TAXES_PAYABLE,
  TIPS,
  UNEARNED_REVENUE,
  UNDEPOSITED_OUTFLOWS,
  OUTGOING_PAYMENT_CLEARING_ACCOUNT,
  OTHER_CURRENT_LIABILITY,
  SHAREHOLDER_LOAN,
  NOTES_PAYABLE,
  OTHER_LONG_TERM_LIABILITIES,

  // EQUITY
  CONTRIBUTIONS,
  DISTRIBUTIONS,
  COMMON_STOCK,
  ADDITIONAL_PAID_IN_CAPITAL,
  RETAINED_EARNINGS,
  ACCUMULATED_ADJUSTMENTS,
  OPENING_BALANCE_EQUITY,
  OTHER_EQUITY,

  // REVENUE
  SALES,
  REVENUE,
  UNCATEGORIZED_REVENUE,
  RETURNS_ALLOWANCES,
  OTHER_INCOME,

  // EXPENSES
  COGS,
  OPERATING_EXPENSES,
  PAYROLL,
  INTEREST_EXPENSES,
  TAXES_LICENSES,
  UNCATEGORIZED_EXPENSE,
}
