import { Vendor } from '../types/vendors'

export const VENDORS_MOCK: Vendor[] = [
  {
    id: '1',
    external_id: 'V001',
    company_name: 'TechCorp Solutions',
    email: 'accounts@techcorp.com',
    office_phone: '(415) 555-0101',
    address_string: '123 Market St, San Francisco, CA 94105',
    status: 'ACTIVE',
  },
  {
    id: '2',
    external_id: 'V002',
    individual_name: 'Sarah Johnson',
    email: 'sarah.j@freelance.com',
    mobile_phone: '(650) 555-0202',
    address_string: '456 Oak Ave, Palo Alto, CA 94301',
    status: 'ACTIVE',
  },
  {
    id: '3',
    external_id: 'V003',
    company_name: 'Global Logistics Inc',
    email: 'billing@globallogistics.com',
    office_phone: '(408) 555-0303',
    address_string: '789 Industrial Pkwy, San Jose, CA 95131',
    notes: 'Preferred shipping partner',
    status: 'ACTIVE',
  },
  {
    id: '4',
    external_id: 'V004',
    company_name: 'Very Creative Design Studio Located in Oakland, Art Street',
    email: 'accounts@creativedesign.co',
    office_phone: '(510) 555-0404',
    address_string: '321 Art Street, Oakland, CA 94612',
    status: 'ARCHIVED',
  },
  {
    id: '5',
    external_id: 'V005',
    individual_name: 'Michael Chen',
    email: 'mike.chen@consulting.net',
    mobile_phone: '(925) 555-0505',
    address_string: '567 Consulting Drive, Walnut Creek, CA 94596',
    notes: 'IT Consultant',
    status: 'ACTIVE',
  },
  {
    id: '6',
    external_id: 'V006',
    company_name: 'Office Supply Pro',
    email: 'orders@officesupplypro.com',
    office_phone: '(415) 555-0606',
    address_string: '890 Supply Road, South SF, CA 94080',
    status: 'ACTIVE',
  },
  {
    id: '7',
    external_id: 'V007',
    individual_name: 'Emma Rodriguez',
    email: 'emma.r@freelance.com',
    mobile_phone: '(415) 555-0707',
    status: 'ARCHIVED',
  },
  {
    id: '8',
    external_id: 'V008',
    company_name: 'Clean & Green Services',
    email: 'service@cleangreen.com',
    office_phone: '(650) 555-0808',
    address_string: '123 Green St, Mountain View, CA 94041',
    status: 'ACTIVE',
  },
  {
    id: '9',
    external_id: 'V009',
    company_name: 'Data Security Solutions',
    email: 'billing@datasecurity.io',
    office_phone: '(408) 555-0909',
    address_string: '456 Cyber Lane, Sunnyvale, CA 94086',
    notes: 'Security software provider',
    status: 'ACTIVE',
  },
  {
    id: '10',
    external_id: 'V010',
    individual_name: 'David Smith',
    email: 'david.smith@contractor.com',
    mobile_phone: '(510) 555-1010',
    address_string: '789 Contractor Circle, Berkeley, CA 94704',
    status: 'ACTIVE',
  },
  {
    id: '11',
    external_id: 'V011',
    company_name: 'Print Masters Co',
    email: 'orders@printmasters.com',
    office_phone: '(925) 555-1111',
    address_string: '321 Print Way, Dublin, CA 94568',
    status: 'ACTIVE',
  },
  {
    id: '12',
    external_id: 'V012',
    individual_name: 'Lisa Wong',
    email: 'lisa.wong@design.com',
    mobile_phone: '(415) 555-1212',
    notes: 'Graphic designer',
    status: 'ACTIVE',
  },
  {
    id: '13',
    external_id: 'V013',
    company_name: 'Bay Area Catering',
    email: 'events@bayareacatering.com',
    office_phone: '(650) 555-1313',
    address_string: '567 Food Court, San Mateo, CA 94403',
    status: 'ARCHIVED',
  },
  {
    id: '14',
    external_id: 'V014',
    company_name: 'Smart Building Systems',
    email: 'support@smartbuilding.com',
    office_phone: '(408) 555-1414',
    address_string: '890 Tech Park, Santa Clara, CA 95051',
    status: 'ACTIVE',
  },
  {
    id: '15',
    external_id: 'V015',
    individual_name: 'Robert Taylor',
    email: 'rob.taylor@maintenance.net',
    mobile_phone: '(510) 555-1515',
    address_string: '123 Service Ave, Fremont, CA 94539',
    status: 'ACTIVE',
  },
  {
    id: '16',
    external_id: 'V016',
    company_name: 'Cloud Infrastructure Corp',
    email: 'billing@cloudinfra.com',
    office_phone: '(415) 555-1616',
    address_string: '456 Cloud Street, SF, CA 94107',
    notes: 'Cloud services provider',
    status: 'ACTIVE',
  },
  {
    id: '17',
    external_id: 'V017',
    individual_name: 'Amanda Lee',
    email: 'amanda.lee@legal.com',
    mobile_phone: '(650) 555-1717',
    address_string: '789 Law Street, Redwood City, CA 94063',
    notes: 'Legal consultant',
    status: 'ACTIVE',
  },
  {
    id: '18',
    external_id: 'V018',
    company_name: 'Marketing Wizards',
    email: 'team@marketingwizards.com',
    office_phone: '(408) 555-1818',
    status: 'ARCHIVED',
  },
  {
    id: '19',
    external_id: 'V019',
    company_name: 'Network Solutions Plus',
    email: 'support@networksolutions.net',
    office_phone: '(925) 555-1919',
    address_string: '321 Network Drive, Pleasanton, CA 94588',
    status: 'ACTIVE',
  },
  {
    id: '20',
    external_id: 'V020',
    individual_name: 'James Wilson',
    email: 'james.wilson@consulting.com',
    mobile_phone: '(415) 555-2020',
    address_string: '567 Consultant Way, SF, CA 94105',
    status: 'ACTIVE',
  },
]
