import i18next from 'i18next'

export const US_STATES = [
  { value: 'AL', label: i18next.t('alabama', 'Alabama') },
  { value: 'AK', label: i18next.t('alaska', 'Alaska') },
  { value: 'AZ', label: i18next.t('arizona', 'Arizona') },
  { value: 'AR', label: i18next.t('arkansas', 'Arkansas') },
  { value: 'CA', label: i18next.t('california', 'California') },
  { value: 'CO', label: i18next.t('colorado', 'Colorado') },
  { value: 'CT', label: i18next.t('connecticut', 'Connecticut') },
  { value: 'DE', label: i18next.t('delaware', 'Delaware') },
  { value: 'DC', label: i18next.t('districtOfColumbia', 'District of Columbia') },
  { value: 'FL', label: i18next.t('florida', 'Florida') },
  { value: 'GA', label: i18next.t('georgia', 'Georgia') },
  { value: 'HI', label: i18next.t('hawaii', 'Hawaii') },
  { value: 'ID', label: i18next.t('idaho', 'Idaho') },
  { value: 'IL', label: i18next.t('illinois', 'Illinois') },
  { value: 'IN', label: i18next.t('indiana', 'Indiana') },
  { value: 'IA', label: i18next.t('iowa', 'Iowa') },
  { value: 'KS', label: i18next.t('kansas', 'Kansas') },
  { value: 'KY', label: i18next.t('kentucky', 'Kentucky') },
  { value: 'LA', label: i18next.t('louisiana', 'Louisiana') },
  { value: 'ME', label: i18next.t('maine', 'Maine') },
  { value: 'MD', label: i18next.t('maryland', 'Maryland') },
  { value: 'MA', label: i18next.t('massachusetts', 'Massachusetts') },
  { value: 'MI', label: i18next.t('michigan', 'Michigan') },
  { value: 'MN', label: i18next.t('minnesota', 'Minnesota') },
  { value: 'MS', label: i18next.t('mississippi', 'Mississippi') },
  { value: 'MO', label: i18next.t('missouri', 'Missouri') },
  { value: 'MT', label: i18next.t('montana', 'Montana') },
  { value: 'NE', label: i18next.t('nebraska', 'Nebraska') },
  { value: 'NV', label: i18next.t('nevada', 'Nevada') },
  { value: 'NH', label: i18next.t('newHampshire', 'New Hampshire') },
  { value: 'NJ', label: i18next.t('newJersey', 'New Jersey') },
  { value: 'NM', label: i18next.t('newMexico', 'New Mexico') },
  { value: 'NY', label: i18next.t('newYork', 'New York') },
  { value: 'NC', label: i18next.t('northCarolina', 'North Carolina') },
  { value: 'ND', label: i18next.t('northDakota', 'North Dakota') },
  { value: 'OH', label: i18next.t('ohio', 'Ohio') },
  { value: 'OK', label: i18next.t('oklahoma', 'Oklahoma') },
  { value: 'OR', label: i18next.t('oregon', 'Oregon') },
  { value: 'PA', label: i18next.t('pennsylvania', 'Pennsylvania') },
  { value: 'RI', label: i18next.t('rhodeIsland', 'Rhode Island') },
  { value: 'SC', label: i18next.t('southCarolina', 'South Carolina') },
  { value: 'SD', label: i18next.t('southDakota', 'South Dakota') },
  { value: 'TN', label: i18next.t('tennessee', 'Tennessee') },
  { value: 'TX', label: i18next.t('texas', 'Texas') },
  { value: 'UT', label: i18next.t('utah', 'Utah') },
  { value: 'VT', label: i18next.t('vermont', 'Vermont') },
  { value: 'VA', label: i18next.t('virginia', 'Virginia') },
  { value: 'WA', label: i18next.t('washington', 'Washington') },
  { value: 'WV', label: i18next.t('westVirginia', 'West Virginia') },
  { value: 'WI', label: i18next.t('wisconsin', 'Wisconsin') },
  { value: 'WY', label: i18next.t('wyoming', 'Wyoming') },
  { value: 'PR', label: i18next.t('puertoRico', 'Puerto Rico') },
] as const

export type USState = typeof US_STATES[number]
export type USStateCode = USState['value']
