import { Schema } from 'effect'

export enum BankDirectionFilter {
  MONEY_IN = 'MONEY_IN',
  MONEY_OUT = 'MONEY_OUT',
}

export const BankDirectionFilterSchema = Schema.Enums(BankDirectionFilter)

export enum BankTransactionType {
  REVENUE = 'REVENUE',
  LOAN_DISBURSEMENT = 'LOAN_DISBURSEMENT',
  REFUND_RECEIVED = 'REFUND_RECEIVED',
  INCOMING_P2P_TRANSFER = 'INCOMING_P2P_TRANSFER',
  INTRA_ACCOUNT_TRANSFER_IN = 'INTRA_ACCOUNT_TRANSFER_IN',
  CHECK_WITHDRAWAL = 'CHECK_WITHDRAWAL',
  ATM_DEPOSIT = 'ATM_DEPOSIT',
  BANK_DEPOSIT = 'BANK_DEPOSIT',
  BANK_VERIFICATION_TRIAL_CREDIT = 'BANK_VERIFICATION_TRIAL_CREDIT',
  REVERSAL_IN = 'REVERSAL_IN',
  CREDIT_CARD_REWARD = 'CREDIT_CARD_REWARD',
  INTEREST_EARNED = 'INTEREST_EARNED',
  GOVERNMENT_OR_OTHER_GRANT = 'GOVERNMENT_OR_OTHER_GRANT',
  TAX_REFUND = 'TAX_REFUND',
  PURCHASE = 'PURCHASE',
  REFUND_GIVEN = 'REFUND_GIVEN',
  OUTGOING_P2P_TRANSFER = 'OUTGOING_P2P_TRANSFER',
  INTRA_ACCOUNT_TRANSFER_OUT = 'INTRA_ACCOUNT_TRANSFER_OUT',
  CHECK_DEPOSIT = 'CHECK_DEPOSIT',
  ATM_WITHDRAWAL = 'ATM_WITHDRAWAL',
  BANK_WITHDRAWAL = 'BANK_WITHDRAWAL',
  BANKING_FEE = 'BANKING_FEE',
  PAYMENT_PROCESSING_FEE = 'PAYMENT_PROCESSING_FEE',
  BANK_VERIFICATION_TRIAL_DEBIT = 'BANK_VERIFICATION_TRIAL_DEBIT',
  REVERSAL_OUT = 'REVERSAL_OUT',
  LOAN_PAYMENT = 'LOAN_PAYMENT',
  TAX_PAYMENT = 'TAX_PAYMENT',
  NOT_ENOUGH_INFORMATION = 'NOT_ENOUGH_INFORMATION',
}

export const BankTransactionTypeSchema = Schema.Enums(BankTransactionType)
