import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

import { CalendarDate } from '@internationalized/date'
import { BigDecimal, Schema } from 'effect'
import fg from 'fast-glob'

/*
 * Regenerates committed fixture modules by finding every generator.ts file.
 *   `npm run fixtures:generate`             writes the files
 *   `npm run fixtures:generate -- --check`  fails if any file is out of date
 */

const check = process.argv.includes('--check')
const fixturesDir = path.resolve('src/fixtures')
const outDir = path.join(fixturesDir, 'generated')

const readFileOrEmpty = (filePath: string) => {
  try {
    return readFileSync(filePath, 'utf8')
  } catch {
    return ''
  }
}

/*
 * Row data isn't always JSON-safe — Date/BigDecimal/CalendarDate need real
 * constructor calls to round-trip, not JSON.stringify's lossy plain-object
 * form. This walks the value tree emitting TS source, tracking which of
 * those constructors it used so the module only imports what it needs.
 */
type SpecialImport = 'date' | 'bigDecimal' | 'calendarDate'

const serializeValue = (value: unknown, depth: number): { code: string, imports: Set<SpecialImport> } => {
  const pad = '  '.repeat(depth)
  const childPad = '  '.repeat(depth + 1)

  if (value instanceof Date) {
    return { code: `new Date(${JSON.stringify(value.toISOString())})`, imports: new Set(['date']) }
  }

  if (BigDecimal.isBigDecimal(value)) {
    return { code: `BigDecimal.unsafeFromString(${JSON.stringify(BigDecimal.format(value))})`, imports: new Set(['bigDecimal']) }
  }

  if (value instanceof CalendarDate) {
    return { code: `new CalendarDate(${value.year}, ${value.month}, ${value.day})`, imports: new Set(['calendarDate']) }
  }

  if (Array.isArray(value)) {
    if (value.length === 0) return { code: '[]', imports: new Set() }

    const items = value.map(item => serializeValue(item, depth + 1))
    const imports = new Set(items.flatMap(item => [...item.imports]))
    const body = items.map(item => `${childPad}${item.code}`).join(',\n')

    return { code: `[\n${body}\n${pad}]`, imports }
  }

  if (value !== null && typeof value === 'object') {
    const entries = Object.entries(value)
    if (entries.length === 0) return { code: '{}', imports: new Set() }

    const serializedEntries = entries.map(([key, entryValue]) => {
      const serialized = serializeValue(entryValue, depth + 1)
      return { code: `${childPad}${JSON.stringify(key)}: ${serialized.code}`, imports: serialized.imports }
    })
    const imports = new Set(serializedEntries.flatMap(entry => [...entry.imports]))

    return { code: `{\n${serializedEntries.map(entry => entry.code).join(',\n')}\n${pad}}`, imports }
  }

  return { code: JSON.stringify(value), imports: new Set() }
}

const SPECIAL_IMPORT_STATEMENTS: Record<SpecialImport, string> = {
  date: '',
  bigDecimal: "import { BigDecimal } from 'effect'",
  calendarDate: "import { CalendarDate } from '@internationalized/date'",
}

const renderFixtureModule = (
  rows: readonly unknown[],
  domain: string,
): string => {
  const { code, imports } = serializeValue(rows, 0)
  const importLines = [...imports].map(name => SPECIAL_IMPORT_STATEMENTS[name]).filter(Boolean).sort()

  return [
    '/* AUTO-GENERATED by `npm run fixtures:generate`. Do not edit by hand. */',
    `import type { schema } from '@fixtures/${domain}/schema'`,
    ...importLines,
    '',
    `export const ${domain} = ${code} as (typeof schema.Type)[]`,
    '',
  ].join('\n')
}

async function main() {
  const generatorFiles = fg
    .sync('*/generator.ts', { cwd: fixturesDir, absolute: true })
    .sort()

  let drifted = false

  for (const generatorFile of generatorFiles) {
    const domain = path.basename(path.dirname(generatorFile))

    // domain becomes an export name and import path in the generated module.
    if (!/^[A-Za-z_$][\w$]*$/.test(domain)) {
      throw new Error(
        `Fixture folder "${domain}" must be a valid identifier (it becomes the exported const name).`,
      )
    }

    const generatorModule = (await import(generatorFile)) as {
      generator?: () => unknown[]
    }

    if (typeof generatorModule.generator !== 'function') {
      throw new Error(
        `src/fixtures/${domain}/generator.ts must export a \`generator\` (createGenerator(...))`,
      )
    }

    const schemaFile = path.join(path.dirname(generatorFile), 'schema.ts')
    const schemaModule = (await import(schemaFile)) as {
      schema?: Schema.Schema<unknown, unknown>
    }

    if (schemaModule.schema == null) {
      throw new Error(`src/fixtures/${domain}/schema.ts must export a \`schema\``)
    }

    const rows = generatorModule.generator()

    // Stands in for the compile-time check the emitted `as` cast bypasses.
    const validateRow = Schema.validateSync(schemaModule.schema)
    rows.forEach((row, index) => {
      try {
        validateRow(row)
      }
      catch (error) {
        throw new Error(
          `src/fixtures/${domain}: generated row ${index} failed schema validation: `
          + (error instanceof Error ? error.message : String(error)),
        )
      }
    })

    const contents = renderFixtureModule(rows, domain)
    const outPath = path.join(outDir, `${domain}.gen.ts`)

    if (check) {
      if (readFileOrEmpty(outPath) !== contents) {
        drifted = true
        console.error(`✗ ${domain}.gen.ts is out of date — run \`npm run fixtures:generate\``)
      }
      continue
    }

    mkdirSync(outDir, { recursive: true })
    writeFileSync(outPath, contents)
    console.log(`Wrote ${rows.length} rows to ${domain}.gen.ts`)
  }

  if (check && drifted) {
    process.exit(1)
  }
}

void main()
