import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

import fg from 'fast-glob'

/*
 * Regenerates committed fixture modules by finding every generator.ts file.
 *   `npm run fixtures:generate`             writes the files
 *   `npm run fixtures:generate -- --check`  fails if any file is out of date
 */

const check = process.argv.includes('--check')
const fixturesDir = path.resolve('src/fixtures')
const outDir = path.join(fixturesDir, 'generated')

const readFileOrEmpty = (filePath: string) => {
  try {
    return readFileSync(filePath, 'utf8')
  } catch {
    return ''
  }
}

const renderFixtureModule = (
  rows: readonly unknown[],
  domain: string,
): string => {
  return [
    '/* AUTO-GENERATED by `npm run fixtures:generate`. Do not edit by hand. */',
    `import type { schema } from '@fixtures/${domain}/schema'`,
    '',
    `export const ${domain}: (typeof schema.Type)[] = ${JSON.stringify(rows, null, 2)}`,
    '',
  ].join('\n')
}

async function main() {
  const generatorFiles = fg
    .sync('*/generator.ts', { cwd: fixturesDir, absolute: true })
    .sort()

  let drifted = false

  for (const generatorFile of generatorFiles) {
    const domain = path.basename(path.dirname(generatorFile))
    const generatorModule = (await import(generatorFile)) as {
      generator?: () => unknown[]
    }

    if (typeof generatorModule.generator !== 'function') {
      throw new Error(
        `src/fixtures/${domain}/generator.ts must export a \`generator\` (createGenerator(...))`,
      )
    }

    const rows = generatorModule.generator()
    const contents = renderFixtureModule(rows, domain)
    const outPath = path.join(outDir, `${domain}.gen.ts`)

    if (check) {
      if (readFileOrEmpty(outPath) !== contents) {
        drifted = true
        console.error(`✗ ${domain}.gen.ts is out of date — run \`npm run fixtures:generate\``)
      }
      continue
    }

    mkdirSync(outDir, { recursive: true })
    writeFileSync(outPath, contents)
    console.log(`Wrote ${rows.length} rows to ${domain}.gen.ts`)
  }

  if (check && drifted) {
    process.exit(1)
  }
}

void main()
