import { Plugin } from 'vite'

const STUB_ID = '\0layer-empty-style'

/**
 * Resolves every `.css`/`.scss` import to one shared empty module.
 *
 * The published stylesheet is generated by the ESM build (`bundleCss`), so the CJS build has no
 * reason to process styles at all. It also cannot: under `preserveModules` each stylesheet becomes
 * its own output module, and Vite's CSS placeholder for those emits `const require_X = ;` in CJS
 * format — a syntax error that makes the whole build unloadable. Collapsing them to a single stub
 * avoids both that and ~270 stray `.css` files under `dist/cjs`.
 */
export function stubStyles(): Plugin {
  return {
    name: 'stub-styles',
    apply: 'build',
    enforce: 'pre',
    resolveId(source) {
      if (source === STUB_ID) return STUB_ID
      return /\.(css|scss)$/.test(source) ? STUB_ID : null
    },
    load(id) {
      return id === STUB_ID ? 'export {}' : null
    },
  }
}
